/* MANUTENCAO DOS DADOS NAS TABELAS
	Inclusão e formas, Alteração e Exclusão de dados

*/

INSERT INTO [TABELA DE PRODUTOS]
(
[CODIGO DO PRODUTO], 
[NOME DO PRODUTO],
[EMBALAGEM],
[TAMANHO],
[SABOR],
[PRECO DE LISTA]
)

VALUES
('1040107','Light - 350ml - Melância','Lata','350ml','Melância',4.56);

SELECT * FROM [TABELA DE PRODUTOS];


INSERT INTO [TABELA DE VENDEDORES]
(
[MATRICULA],
[NOME],
[PERCENTUAL COMISSAO]
)

VALUES
('00235','Márcio Almeida Silva', 0.08);


INSERT INTO [TABELA DE PRODUTOS]
(
[CODIGO DO PRODUTO], 
[NOME DO PRODUTO],
[EMBALAGEM],
[TAMANHO],
[SABOR],
[PRECO DE LISTA]
)

VALUES
('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01);

INSERT INTO [TABELA DE PRODUTOS]
(
[CODIGO DO PRODUTO], 
[NOME DO PRODUTO],
[EMBALAGEM],
[TAMANHO],
[SABOR],
[PRECO DE LISTA]
)

VALUES
('1000889','Sabor da Montanha - 700ml - Uva','Garrafa','700ml','Uva',6.31);

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('1004327','Videira do Campo - 1,5 Litros - Melância','PET','1,5 Litros','Melância',19.51);

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7),
('544931','Frescor do Verão - 350 ml - Limão','Lata','350ml','Limão',2.46);

INSERT INTO [TABELA DE VENDEDORES]
VALUES
('00236','Cláudia Morais', 0.08),
('00237','Marcela Ferreira', 0.09);



UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = 3
WHERE [CODIGO DO PRODUTO] = '544931';

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = 7.50,[EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1088126';

UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00235';

UPDATE [TABELA DE VENDEDORES]
SET [NOME] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = '00236';



DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327';

DELETE FROM [TABELA DE VENDEDORES]
WHERE [MATRICULA] = '00236';
