/* ORDEM DOS CAMPOS E CHAVE PRIMÁRIA
	Nulos, PK, Campo data e lógico

*/

-- TABELA DE PRODUTOS
  SELECT * FROM [TABELA DE PRODUTOS]
  ALTER TABLE [TABELA DE PRODUTOS] ALTER COLUMN [CODIGO DO PRODUTO] VARCHAR (20) NOT NULL;

  ALTER TABLE [TABELA DE PRODUTOS] ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
  PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);


  
  -- TABELA DE VENDEDORES
  SELECT * FROM [TABELA DE VENDEDORES]
  ALTER TABLE [TABELA DE VENDEDORES] ALTER COLUMN [MATRICULA] VARCHAR (5) NOT NULL;

  ALTER TABLE [TABELA DE VENDEDORES] ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
  PRIMARY KEY CLUSTERED ([MATRICULA]);

    DROP TABLE [TABELA DE VENDEDORES]; 

 -- item 2
CREATE TABLE [TABELA DE VENDEDORES](
    [MATRICULA] [varchar](5) NOT NULL,
    [NOME] [varchar](100) NULL,
    [CIDADE] [varchar](100) NULL,
    [PERCENTUAL COMISSÃO] [FLOAT] NOT NULL,
    [DATA INICIO] [date] NOT NULL,
    [TEM DEPENDENTE] [BIT]);

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA]);

 -- item 3
INSERT INTO [TABELA DE VENDEDORES]
([NOME], 
[MATRICULA],
[CIDADE],
[PERCENTUAL COMISSÃO],
[DATA INICIO],
[TEM DEPENDENTE])
VALUES
('Alberto de Sá Verneck','00239','São Paulo', 0.08,'2020-06-05',1);

 -- item 4
SELECT * FROM [TABELA DE VENDEDORES];

INSERT INTO [TABELA DE VENDEDORES]
([NOME], 
[MATRICULA],
[CIDADE],
[PERCENTUAL COMISSÃO],
[DATA INICIO],
[TEM DEPENDENTE])
VALUES
('Marcela Almeida','00240','Rio de Janeiro', 0.07,'2021-01-12','FALSE');


  -- TABELA DE CLIENTES
  SELECT * FROM [TABELA DE CLIENTES]
  ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN [CPF] VARCHAR (11) NOT NULL;

  ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_DE_CLIENTES
  PRIMARY KEY CLUSTERED ([CPF]);

  INSERT INTO [TABELA DE CLIENTES]
  VALUES
  ('38650005844','Beatriz Sousa','Rua Sargento','Numero 200','Jardim Imperador',
  'São Paulo','SP','03937001','1994-01-12',29,'F',200000,3000.30,1);

  INSERT INTO [TABELA DE CLIENTES]
  VALUES
  ('38650005828','Patricia Sousa','Rua Sargento','Numero 200','Jardim Imperador',
  'São Paulo','SP','03937001','1994-01-12',29,'F',200000,3000.30,'TRUE');

  INSERT INTO [TABELA DE CLIENTES]
  VALUES
  ('38650005852','Flavia Sousa','Rua Sargento','Numero 200','Jardim Imperador',
  'São Paulo','SP','03937001','1994-01-12',29,'F',200000,3000.30,'FALSE');

  SELECT * FROM [TABELA DE CLIENTES];

